name: Multi-Target Build
on:
  push:
    branches: ["master"]
env:
  GIT_TERMINAL_PROMPT: 0  # 禁用终端提示
  GIT_SUBMODULE_STRATEGY: recursive  # 强制递归初始化子模块
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate target matrix
        id: set-matrix
        run: |
          # 定义目标列表
          TARGETS='["k2b_h618", "rk3399_custom"]'
          echo "matrix=$TARGETS" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.matrix) }}
    name: Build ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Initialization environment and Free up disk space
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/cache/apt/archives/*
          sudo rm -rf /var/cache/debconf/*-old
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo apt clean
          sudo rm -rf /etc/apt/sources.list.d/*
          sudo apt-get -qq update -y
          sudo apt-get -qq autoremove --purge -y
          sudo apt-get -qq clean -y
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          #sudo rm -rf /usr/share/
          df -h
      - name: Write keys
        run: |
          echo "${{ secrets.MID_KEY_PEM }}" > ./operating-system/key.pem
          echo "${{ secrets.MID_CERT_PEM }}" > ./operating-system/cert.pem

      - name: Build HAOS-ACE with retry
        shell: 'script -q -e -c "bash {0}"'
        run: |

          max_retries=3
          count=0
          until ./build.sh ${{ matrix.target }}; do
            count=$((count+1))
            [[ $count -ge $max_retries ]] && exit 1
            sleep 30
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: output/images/haos*

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: output/images/haos*
          tag_name: ${{ github.ref_name }}
          name: "Haos-ace Release ${{ github.ref_name }} (${{ steps.date.outputs.DATE }})"
          body: |
            自动化构建的应用服务，包含以下文件：
            - haos*.img.xz  压缩烧写镜像
            - haos*.raucb   OTA 更新包

            * 版本: ${{ github.ref_name }}
            * Commit: ${{ github.sha }}
            * 版本信息: 
              ${{ github.event.head_commit.message }}
            * 提交者: ${{ github.event.head_commit.author.name }}
          draft: false